import LeftSide from "@/components/LeftSide";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
    <Head>
      <title>Subhajit.dev</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="public/logo.ico" />
    </Head>
      <main className="w-full h-screen font-bodyFont bg-slate-900 text-textLight overflow-x-hidden overflow-y-scroll">
        <Navbar/>

        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
        <div className="hidden xl:inline-flex w-32 h-full fixed bottom-[150px]">
          <LeftSide/>
        </div>
        <div className="h-[88vh] mx-auto p-4">
        
        </div>
        </div>
      </main>
    
    </>
    
  )
}
