import LeftSide from "@/components/LeftSide";
import RightSide from "@/components/RightSide";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { motion } from "framer-motion";
import About from "@/components/About";
export default function Home() {
  return (
    <>
    <Head>
      <title>Subhajit.dev</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="public/logo.ico" />
    </Head>
      <main className="w-full h-screen font-bodyFont bg-slate-900 text-textLight overflow-x-hidden overflow-y-scroll">
        <Navbar/>

        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
        <motion.div initial={{opacity : 0}} animate={{opacity : 1}} transition={{delay : 1.5}} className="hidden xl:inline-flex w-32 h-full fixed bottom-[150px]">
          <LeftSide/>
        </motion.div>
        <div className="h-[88vh] mx-auto p-4">
         <RightSide/>

         {/* About */}
         <About/>
         {/* Experience */}
         {/* Projects */}
          {/* Contact */}
          {/* Footer */}
        </div>
        </div>
      </main>
    
    </>
    
  )
}
